# Generated by Django 3.2 on 2021-04-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
